name: project
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aiohappyeyeballs=2.6.1=py312h06a4308_0
  - anyio=4.7.0=py312h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py312h5eee18b_1
  - arrow-cpp=19.0.0=h865e1df_2
  - asttokens=3.0.0=py312h06a4308_0
  - async-lru=2.0.4=py312h06a4308_0
  - attrs=24.3.0=py312h06a4308_0
  - aws-c-auth=0.6.19=h5eee18b_0
  - aws-c-cal=0.5.20=hdbd6064_0
  - aws-c-common=0.8.5=h5eee18b_0
  - aws-c-compression=0.2.16=h5eee18b_0
  - aws-c-event-stream=0.2.15=h6a678d5_0
  - aws-c-http=0.6.25=h5eee18b_0
  - aws-c-io=0.13.10=h5eee18b_0
  - aws-c-mqtt=0.7.13=h5eee18b_0
  - aws-c-s3=0.1.51=hdbd6064_0
  - aws-c-sdkutils=0.1.6=h5eee18b_0
  - aws-checksums=0.1.13=h5eee18b_0
  - aws-crt-cpp=0.18.16=h6a678d5_0
  - aws-sdk-cpp=1.11.212=hecad206_0
  - babel=2.16.0=py312h06a4308_0
  - beautifulsoup4=4.12.3=py312h06a4308_0
  - blas=1.0=mkl
  - bleach=6.2.0=py312h06a4308_0
  - boost-cpp=1.82.0=hdb19cb5_2
  - bottleneck=1.4.2=py312ha883a20_0
  - brotli-python=1.0.9=py312h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.2.25=h06a4308_0
  - certifi=2025.4.26=py312h06a4308_0
  - cffi=1.17.1=py312h1fdaa30_1
  - cfgv=3.4.0=py312h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - comm=0.2.1=py312h06a4308_0
  - contourpy=1.3.1=py312hdb19cb5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - datasets=3.3.2=py312h06a4308_0
  - debugpy=1.8.11=py312h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - dill=0.3.8=py312h06a4308_0
  - distlib=0.3.8=py312h06a4308_0
  - et_xmlfile=1.1.0=py312h06a4308_1
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.7.1=h6a678d5_0
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.55.3=py312h5eee18b_0
  - freetype=2.13.3=h4a9f257_0
  - gflags=2.2.2=h6a678d5_1
  - glog=0.5.0=h6a678d5_1
  - h11=0.14.0=py312h06a4308_0
  - hf-xet=1.1.8=py312h84c0859_0
  - httpcore=1.0.2=py312h06a4308_0
  - httpx=0.27.0=py312h06a4308_0
  - icu=73.1=h6a678d5_0
  - identify=2.5.5=py312h06a4308_0
  - idna=3.7=py312h06a4308_0
  - importlib-metadata=8.5.0=py312h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.5=py312h06a4308_1
  - ipython=9.1.0=py312h06a4308_0
  - ipython_pygments_lexers=1.1.1=py312h06a4308_0
  - ipywidgets=8.1.5=py312h06a4308_0
  - jedi=0.19.2=py312h06a4308_0
  - jinja2=3.1.6=py312h06a4308_0
  - joblib=1.4.2=py312h06a4308_0
  - jpeg=9e=h5eee18b_3
  - json5=0.9.25=py312h06a4308_0
  - jsonschema-specifications=2023.7.1=py312h06a4308_0
  - jupyter=1.1.1=py312h06a4308_0
  - jupyter-lsp=2.2.5=py312h06a4308_0
  - jupyter_client=8.6.3=py312h06a4308_0
  - jupyter_console=6.6.3=py312h06a4308_1
  - jupyter_core=5.7.2=py312h06a4308_0
  - jupyter_events=0.12.0=py312h06a4308_0
  - jupyter_server=2.15.0=py312h06a4308_0
  - jupyter_server_terminals=0.5.3=py312h06a4308_0
  - jupyterlab=4.3.4=py312h06a4308_0
  - jupyterlab_pygments=0.3.0=py312h06a4308_0
  - jupyterlab_server=2.27.3=py312h06a4308_0
  - jupyterlab_widgets=3.0.13=py312h06a4308_0
  - kiwisolver=1.4.8=py312h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h5eee18b_9
  - libbrotlidec=1.0.9=h5eee18b_9
  - libbrotlienc=1.0.9=h5eee18b_9
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.12.1=hc9e6f67_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libgrpc=1.71.0=h2d74bed_0
  - libiconv=1.16=h5eee18b_3
  - libnghttp2=1.57.0=h2d74bed_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.4=hdbd6064_0
  - libprotobuf=5.29.3=hc99497a_0
  - libre2-11=2024.07.02=h6a678d5_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libthrift=0.15.0=h1795dd8_2
  - libtiff=4.7.0=hde9077f_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h097e994_2
  - libxml2=2.13.7=hfdd30dd_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py312h5eee18b_0
  - matplotlib=3.10.0=py312h06a4308_0
  - matplotlib-base=3.10.0=py312hbfdbfaf_0
  - matplotlib-inline=0.1.6=py312h06a4308_0
  - mistune=3.1.2=py312h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py312h5eee18b_2
  - mkl_fft=1.3.11=py312h5eee18b_0
  - mkl_random=1.2.8=py312h526ad5a_0
  - multiprocess=0.70.15=py312h06a4308_0
  - mysql=8.4.0=h721767e_2
  - nbclient=0.10.2=py312h06a4308_0
  - nbconvert=7.16.6=py312h06a4308_0
  - nbconvert-core=7.16.6=py312h06a4308_0
  - nbconvert-pandoc=7.16.6=py312h06a4308_0
  - nbformat=5.10.4=py312h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py312h06a4308_0
  - nodeenv=1.9.1=py312h06a4308_0
  - notebook=7.3.2=py312h06a4308_0
  - notebook-shim=0.2.4=py312h06a4308_0
  - numexpr=2.10.1=py312h3c60e43_0
  - openjpeg=2.5.2=h0d4d230_1
  - openldap=2.6.4=h42fbc30_0
  - openpyxl=3.1.5=py312h5eee18b_1
  - openssl=3.0.16=h5eee18b_0
  - orc=2.1.1=hd396ef6_0
  - overrides=7.4.0=py312h06a4308_0
  - packaging=24.2=py312h06a4308_0
  - pandas=2.2.3=py312h6a678d5_0
  - pandoc=2.12=h06a4308_3
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.4=py312h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pillow=11.1.0=py312hac6e08b_1
  - pip=25.0=py312h06a4308_0
  - platformdirs=4.3.7=py312h06a4308_0
  - pre-commit=3.4.0=py312h06a4308_1
  - prometheus_client=0.21.1=py312h06a4308_0
  - prompt-toolkit=3.0.43=py312h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - propcache=0.3.1=py312h5eee18b_0
  - psutil=5.9.0=py312h5eee18b_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyarrow=19.0.0=py312h6a678d5_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.19.1=py312h06a4308_0
  - pyparsing=3.2.0=py312h06a4308_0
  - pyqt=6.7.1=py312h6a678d5_1
  - pyqt6-sip=13.9.1=py312h5eee18b_1
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.3=h996f2a0_1
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - python-fastjsonschema=2.20.0=py312h06a4308_0
  - python-json-logger=3.2.1=py312h06a4308_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python-xxhash=3.5.0=py312h5eee18b_0
  - pytz=2024.1=py312h06a4308_0
  - pyyaml=6.0.2=py312h5eee18b_0
  - pyzmq=26.2.0=py312h6a678d5_0
  - qtbase=6.7.3=hdaa5aa8_0
  - qtconsole=5.6.1=py312h06a4308_1
  - qtdeclarative=6.7.3=h6a678d5_0
  - qtpy=2.4.1=py312h06a4308_0
  - qtsvg=6.7.3=he621ea3_0
  - qttools=6.7.3=h80c7b02_0
  - qtwebchannel=6.7.3=h6a678d5_0
  - qtwebsockets=6.7.3=h6a678d5_0
  - re2=2024.07.02=hdb19cb5_0
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=py312h06a4308_0
  - regex=2024.11.6=py312h5eee18b_0
  - requests=2.32.3=py312h06a4308_1
  - rfc3339-validator=0.1.4=py312h06a4308_0
  - rfc3986-validator=0.1.1=py312h06a4308_0
  - rpds-py=0.22.3=py312h4aa5aa6_0
  - s2n=1.3.27=hdbd6064_0
  - safetensors=0.5.3=py312hc50d6dc_0
  - scikit-learn=1.6.1=py312h6a678d5_0
  - scipy=1.15.2=py312h23a989f_1
  - seaborn=0.13.2=py312h06a4308_2
  - send2trash=1.8.2=py312h06a4308_1
  - setuptools=75.8.0=py312h06a4308_0
  - sip=6.10.0=py312h6a678d5_0
  - six=1.17.0=py312h06a4308_0
  - snappy=1.2.1=h6a678d5_0
  - sniffio=1.3.0=py312h06a4308_0
  - soupsieve=2.5=py312h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=hdb19cb5_0
  - terminado=0.17.1=py312h06a4308_0
  - threadpoolctl=3.5.0=py312he106c6f_0
  - tinycss2=1.4.0=py312h06a4308_0
  - tk=8.6.14=h39e8969_0
  - tokenizers=0.19.1=py312ha11519a_0
  - tornado=6.4.2=py312h5eee18b_0
  - tqdm=4.67.1=py312he106c6f_0
  - traitlets=5.14.3=py312h06a4308_0
  - transformers=4.44.1=py312h06a4308_0
  - typing-extensions=4.12.2=py312h06a4308_0
  - typing_extensions=4.12.2=py312h06a4308_0
  - tzdata=2025a=h04d1e81_0
  - ukkonen=1.0.1=py312hdb19cb5_1
  - unicodedata2=15.1.0=py312h5eee18b_1
  - urllib3=2.3.0=py312h06a4308_0
  - utf8proc=2.6.1=h5eee18b_1
  - virtualenv=20.28.0=py312h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py312h06a4308_2
  - websocket-client=1.8.0=py312h06a4308_0
  - wheel=0.45.1=py312h06a4308_0
  - widgetsnbextension=4.0.13=py312h06a4308_0
  - xcb-util-cursor=0.1.4=h5eee18b_0
  - xxhash=0.8.0=h7f8727e_3
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.21.0=py312h06a4308_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - arrow==1.4.0
      - boolean-py==5.0
      - chardet==5.2.0
      - click==8.1.8
      - cyclonedx-bom==7.2.1
      - cyclonedx-python-lib==11.5.0
      - dicom2jpg==0.1.10
      - docker-pycreds==0.4.0
      - filelock==3.13.1
      - fqdn==1.5.1
      - frozenlist==1.6.0
      - fsspec==2024.6.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - huggingface-hub==0.30.2
      - hydra-core==1.3.2
      - imageio==2.37.0
      - isoduration==20.11.0
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - lark==1.3.1
      - lazy-loader==0.4
      - license-expression==30.4.4
      - lightning==2.5.1.post0
      - lightning-utilities==0.14.3
      - lxml==6.0.2
      - monai==1.4.0
      - mpmath==1.3.0
      - multidict==6.4.3
      - networkx==3.3
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nvtx-cu11==11.8.86
      - omegaconf==2.3.0
      - opencv-python==4.11.0.86
      - packageurl-python==0.17.5
      - pip-requirements-parser==32.0.1
      - protobuf==5.29.4
      - py-serializable==2.1.0
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - pydicom==3.0.1
      - pylibjpeg==2.0.1
      - pylibjpeg-libjpeg==2.2.0
      - pylibjpeg-openjpeg==2.3.0
      - python-dotenv==1.1.0
      - pytorch-lightning==2.5.1.post0
      - rfc3987-syntax==1.1.0
      - rootutils==1.0.7
      - scikit-image==0.25.2
      - sentry-sdk==2.27.0
      - setproctitle==1.3.5
      - smmap==5.0.2
      - sortedcontainers==2.4.0
      - sympy==1.13.3
      - tifffile==2025.9.9
      - timm==1.0.15
      - torch==2.7.0+cu118
      - torchaudio==2.7.0+cu118
      - torchmetrics==1.7.1
      - torchvision==0.22.0+cu118
      - torchxrayvision==1.4.0
      - triton==3.3.0
      - typing-inspection==0.4.0
      - uri-template==1.3.0
      - wandb==0.19.1
      - webcolors==25.10.0
      - yarl==1.20.0
prefix: /mnt/nfs/homedirs/benjamins/miniconda3/envs/project
